version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=passwordhere
    # entrypoint: [ "/usr/share/elasticsearch/bin/elasticsearch-plugin", "install", "analysis-icu", "&&", "/usr/share/elasticsearch/bin/elasticsearch", "-d" ]
    volumes:
      - ./data:/usr/share/elasticsearch/data
    command:
      - /bin/sh
      - -c
      - |
          /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
          exec /usr/local/bin/docker-entrypoint.sh eswrapper
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=passwordhere
    ports:
      - "5601:5601"