version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.2
    volumes:
      - ./data1/db:/data/db
      - ./data1/configdb:/data/configdb
      - ./keyfile:/opt/mongors/keyfile
    networks:
      - mongo-replica-net
    expose:
      - 30001
    ports:
      - 30001:30001
    restart: always
    entrypoint: [ "mongod","--port", "30001", "--auth", "--keyFile", "/opt/mongors/keyfile", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.2
    volumes:
      - ./data2/db:/data/db
      - ./data2/configdb:/data/configdb
      - ./keyfile:/opt/mongors/keyfile
    networks:
      - mongo-replica-net
    expose:
      - 30002
    ports:
      - 30002:30002
    restart: always
    entrypoint: [ "mongod","--port", "30002", "--auth", "--keyFile", "/opt/mongors/keyfile", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.2
    volumes:
      - ./data3/db:/data/db
      - ./data3/configdb:/data/configdb
      - ./keyfile:/opt/mongors/keyfile
    networks:
      - mongo-replica-net
    expose:
      - 30003
    ports:
      - 30003:30003
    restart: always
    entrypoint: [ "mongod","--port", "30003", "--auth", "--keyFile", "/opt/mongors/keyfile", "--bind_ip_all", "--replSet", "rs0" ]
networks:
  mongo-replica-net: